### ISSUE TITLE
Improve "no target snapshot/match error" message

### ISSUE THREAD

**Issue by yonas** [bellhyve/zelta#43]
```sh
$ zelta backup zroot/tmp zroot/test
no target snapshot: zroot/test
match error
```

```sh
$ zfs list
...
zroot                                         2.66G  3.64G    96K  /zroot
zroot/test                                      96K  3.64G    96K  /zroot/test
zroot/tmp                                      164K  3.64G   164K  /tmp
```

**Comment by bellhyve** [comment]
This error definitely needs to be clearer. The target (`zroot/test`) should not exist or be a replica of the source (`zroot/tmp`) that you're updating. Otherwise, there is no delta to replicate. To clarify:

- a full stream needs to go to a new dataset that doesn't exist
- an incremental stream must update an existing replica

```sh
# zfs create boot07/test
# zelta backup boot07/tmp boot07/test
no target snapshot: boot07/test
match error
# zelta backup boot07/tmp boot07/test2                                                                                                   (5)
replicating 2 streams
1M sent, 2/2 streams received in 0.18 seconds
```

I think the error should be something like: `target dataset exists and cannot be updated`

How does that sound?

**Comment by yonas** [comment]
@bellhyve Thanks, that sounds fine. It does work when the target doesn't exist.

**Comment by bellhyve** [comment]
Now it tells you that it cannot determine sync state and will tell you if the target is written. That should be a better clue that the target can't be replicated to because it's in the way. I'm going to close this but will try to continue improving the error messages.
